name: Snapshot Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  buildSnapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: mailspy-frontend/package-lock.json
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Update snapshot version
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: "updateBuildVersion"
      - name: Read version
        id: read_version
        uses: andstor/file-reader-action@v1
        with:
          path: build/version.txt
      - name: Verify and build
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: "check bootJar bootWar -PincludeFrontend"
      - name: Collect line coverage metrics
        id: collect_line_coverage
        run: |
          sudo apt-get install -y libxml2-utils
          total_lines_be=$(xmllint mailspy-core/build/reports/jacoco/test/jacocoTestReport.xml --xpath "number(//report/counter[@type='LINE']/@covered)+number(//report/counter[@type='LINE']/@missed)")
          total_lines_fe=$(xmllint mailspy-frontend/build/reports/coverage/cobertura-coverage.xml --xpath "number(//coverage/@lines-valid)")
          covered_lines_be=$(xmllint mailspy-core/build/reports/jacoco/test/jacocoTestReport.xml --xpath "number(//report/counter[@type='LINE']/@covered)")
          covered_lines_fe=$(xmllint mailspy-frontend/build/reports/coverage/cobertura-coverage.xml --xpath "number(//coverage/@lines-covered)")
          echo "result=$((((covered_lines_be + covered_lines_fe) * 100) / (total_lines_be + total_lines_fe)))" >> $GITHUB_OUTPUT
      - name: Update line coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_ACCESS_TOKEN }}
          gistID: e0159b67e62fe9b4c7657e58419b6cc1
          filename: coverage_badge.json
          label: coverage
          message: "${{ steps.collect_line_coverage.outputs.result }}%"
          valColorRange: "${{ steps.collect_line_coverage.outputs.result }}"
          maxColorRange: 100
          minColorRange: 0
      - name: Setup git user
        uses: fregante/setup-git-user@v1
      - name: Push version update
        run: |
          git pull
          git add .
          git commit -m "Update version to v${{ steps.read_version.outputs.contents }} [skip ci]" || true
          git push -u
