name: Snapshot Build

on:
  push:
    branches: [ "master" ]

jobs:
  buildSnapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: mailspy-frontend/package-lock.json
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Update snapshot version
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: "updateBuildVersion"
      - name: Read version
        id: read_version
        uses: andstor/file-reader-action@v1
        with:
          path: build/version.txt
      - name: Verify and build
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: "check bootJar bootWar"
      - name: Collect total line count for back end coverage
        id: "coverage_total_lines_be"
        uses: QwerMike/xpath-action@v1
        with:
          filename: mailspy-core/build/reports/jacoco/test/jacocoTestReport.xml
          expression: "number(//report/counter[@type='LINE']/@covered)+number(//report/counter[@type='LINE']/@missed)"
      - name: Collect covered line count for back end coverage
        id: "coverage_covered_lines_be"
        uses: QwerMike/xpath-action@v1
        with:
          filename: mailspy-core/build/reports/jacoco/test/jacocoTestReport.xml
          expression: "number(//report/counter[@type='LINE']/@covered)"
      - name: Collect total line count for front end coverage
        id: "coverage_total_lines_fe"
        uses: QwerMike/xpath-action@v1
        with:
          filename: mailspy-frontend/build/reports/coverage/cobertura-coverage.xml
          expression: "number(//coverage/@lines-valid)"
      - name: Collect covered line count for front end coverage
        id: "coverage_covered_lines_fe"
        uses: QwerMike/xpath-action@v1
        with:
          filename: mailspy-frontend/build/reports/coverage/cobertura-coverage.xml
          expression: "number(//coverage/@lines-covered)"
      - name: Setup git user
        uses: fregante/setup-git-user@v1
      - name: Push version update
        run: |
          git add .
          git commit -m "Update version to v${{ steps.read_version.outputs.contents }} [skip ci]" || true
          git push -u
