name: Snapshot Build

on:
  push:
    branches: [ "master" ]

jobs:
  buildSnapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Update snapshot version
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: "updateBuildVersion"
      - name: Read version
        id: read_version
        uses: andstor/file-reader-action@v1
        with:
          path: build/version.txt
      - name: Verify and build
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: "check bootJar bootWar"
      - name: Push version update
        run: |
          git add .
          git commit -m "Update version to v${{ steps.read_version.outputs.contents }}" || true
          git push -u
