name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Invoke Gradle check
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: check
      - name: Report JaCoCo coverage
        uses: PavanMudigonda/jacoco-reporter@v4.5
        with:
          coverage_results_path: mailspy-core/build/reports/jacoco/test/jacocoTestReport.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add coverage report to summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY
